use mydatabase;
select * from mytable;

-- Q1. what is the total revenue generated by male vs female customers?

select gender, sum(purchase_amount) as Total_revenue
from mytable
group by gender;


-- Q2. Which customers used a discount but still spent more then the avergae purchase amount?

select customer_id, purchase_amount
from mytable 
where discount_applied = "Yes"
and purchase_amount > (
select avg(purchase_amount)
from mytable);


-- Q3. Which are the top 5 products with the highest averag review rating?

select item_purchased, round(avg(review_rating),2) as max_avg_rating
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- Q4. Compare the avergae purchase amount between Standard and express shipping?

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from mytable
where shipping_type in ("Standard","Express")
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status ,count(customer_id) as total_count ,round(avg(purchase_amount),2) as avg_purchase_amt ,round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status;



-- Q6. which 5 products have the highest percentage of porchases with discounts applied?

SELECT 
item_purchased,
round(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),2) AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_data as (
select customer_id, previous_purchases,
CASE
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from mytable
)
select customer_segment,count(*) as Number_of_customers
from customer_data
group by customer_segment;



-- Q8. what are the top 3 most purchased products within each category

with total_items as (
select category, item_purchased,
count(customer_id) as total_customer_count,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_ranks
from mytable
group by category, item_purchased
)

select category, item_purchased, item_ranks, total_customer_count
from total_items
where item_ranks<= 3;



-- Q9. Are customers who are repaeat buyers (more then 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyer_count
from mytable
where previous_purchases > 5
group by subscription_status;



-- Q10. What is the revenue contribution of eacn age group?

select age_group, sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;